const content=document.getElementById('content');const side=document.getElementById('side');const menuBtn=document.getElementById('menu-btn');const sideClose=document.getElementById('side-close');const backdrop=document.getElementById('side-backdrop');function setMenu(open){side.classList.toggle('open',open);backdrop.classList.toggle('open',open);document.body.classList.toggle('nav-open',open)}menuBtn?.addEventListener('click',()=>setMenu(!side.classList.contains('open')));sideClose?.addEventListener('click',()=>setMenu(false));backdrop?.addEventListener('click',()=>setMenu(false));
const headings=[...content.querySelectorAll('h2')];
const escapeHtml=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));const articlePath=JSON.parse(document.getElementById('article-meta-json')?.textContent||'{}').path||'';let marked=null;let currentPatch='';let mermaidApi=null;const updatesEl=document.getElementById('article-updates-json');const updates=updatesEl?JSON.parse(updatesEl.textContent):[];const modalBackdrop=document.getElementById('revision-modal-backdrop');const modalBody=document.getElementById('revision-modal-body');
const mermaidKinds=[[/^(flowchart|graph)\b/i,'FLOWCHART'],[/^sequenceDiagram\b/i,'SEQUENCE'],[/^stateDiagram(?:-v2)?\b/i,'STATE'],[/^classDiagram\b/i,'CLASS'],[/^erDiagram\b/i,'ER'],[/^gantt\b/i,'GANTT'],[/^pie\b/i,'PIE'],[/^mindmap\b/i,'MINDMAP'],[/^timeline\b/i,'TIMELINE'],[/^journey\b/i,'JOURNEY'],[/^gitGraph\b/i,'GIT GRAPH'],[/^quadrantChart\b/i,'QUADRANT'],[/^xychart(?:-beta)?\b/i,'XY CHART'],[/^sankey(?:-beta)?\b/i,'SANKEY'],[/^block(?:-beta)?\b/i,'BLOCK'],[/^packet(?:-beta)?\b/i,'PACKET'],[/^architecture(?:-beta)?\b/i,'ARCHITECTURE'],[/^kanban\b/i,'KANBAN'],[/^requirementDiagram\b/i,'REQUIREMENT'],[/^C4\w*\b/i,'C4']];
function mermaidKind(source){const first=String(source||'').split('\n').map(line=>line.trim()).find(line=>line&&!line.startsWith('%%'))||'';return mermaidKinds.find(([pattern])=>pattern.test(first))?.[1]||'DIAGRAM'}
async function getMermaid(){if(mermaidApi)return mermaidApi;const mod=await import('https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs');mermaidApi=mod.default;mermaidApi.initialize({startOnLoad:false,securityLevel:'strict',theme:'base',flowchart:{curve:'linear',htmlLabels:true,useMaxWidth:true,nodeSpacing:44,rankSpacing:54},sequence:{useMaxWidth:true,wrap:true,diagramMarginX:18,diagramMarginY:18,actorMargin:60,messageMargin:40},themeVariables:{fontFamily:'Inter,-apple-system,BlinkMacSystemFont,"Segoe UI","Hiragino Sans","Yu Gothic",Meiryo,sans-serif',fontSize:'16px',background:'#f4fafb',primaryColor:'#fbfefe',primaryTextColor:'#1c343c',primaryBorderColor:'#85aab2',secondaryColor:'#eaf5f7',secondaryTextColor:'#1c343c',secondaryBorderColor:'#85aab2',tertiaryColor:'#dceff2',tertiaryTextColor:'#1c343c',tertiaryBorderColor:'#286b78',textColor:'#1c343c',lineColor:'#4d7b84',mainBkg:'#fbfefe',nodeBorder:'#85aab2',clusterBkg:'#f4fafb',clusterBorder:'#c9dade',titleColor:'#1c343c',edgeLabelBackground:'#f9fcfd',actorBkg:'#fbfefe',actorBorder:'#85aab2',actorTextColor:'#1c343c',actorLineColor:'#9bb9bf',signalColor:'#4d7b84',signalTextColor:'#1c343c',labelBoxBkgColor:'#eaf5f7',labelBoxBorderColor:'#85aab2',labelTextColor:'#1c343c',loopTextColor:'#1c343c',noteBkgColor:'#eaf5f7',noteBorderColor:'#85aab2',noteTextColor:'#1c343c',activationBkgColor:'#dceff2',activationBorderColor:'#286b78',classText:'#1c343c',taskBkgColor:'#5b9aa6',taskBorderColor:'#286b78',taskTextColor:'#173a42',activeTaskBkgColor:'#286b78',activeTaskBorderColor:'#174b56',activeTaskTextColor:'#ffffff',doneTaskBkgColor:'#85aab2',doneTaskBorderColor:'#5b9aa6',doneTaskTextColor:'#173a42',critBkgColor:'#a37b4e',critBorderColor:'#79572f',critTextColor:'#ffffff',todayLineColor:'#286b78',sectionBkgColor:'#f4fafb',altSectionBkgColor:'#eaf5f7',gridColor:'#c9dade',pie1:'#286b78',pie2:'#5d8f77',pie3:'#a37b4e',pie4:'#85aab2',pie5:'#8a6f9b',pie6:'#b36d6a',pie7:'#648a9a',pie8:'#a9a268',pieStrokeColor:'#f9fcfd',pieStrokeWidth:'3px',pieOpacity:'0.96',pieTitleTextSize:'18px',pieLegendTextColor:'#1c343c',pieLegendTextSize:'14px',pieSectionTextColor:'#ffffff',pieSectionTextSize:'13px'}});return mermaidApi}
let mermaidBlueprintSerial=0;
const mermaidBlueprintCss=`
svg.mermaid-svg-blueprint{overflow:visible;background:transparent}
svg.mermaid-svg-blueprint text,svg.mermaid-svg-blueprint tspan,svg.mermaid-svg-blueprint .label,svg.mermaid-svg-blueprint .nodeLabel,svg.mermaid-svg-blueprint .edgeLabel,svg.mermaid-svg-blueprint .messageText,svg.mermaid-svg-blueprint .loopText,svg.mermaid-svg-blueprint .noteText,svg.mermaid-svg-blueprint .classTitle,svg.mermaid-svg-blueprint .entityLabel{font-family:Inter,-apple-system,BlinkMacSystemFont,"Segoe UI","Hiragino Sans","Yu Gothic",Meiryo,sans-serif!important;fill:#1c343c!important;color:#1c343c!important;font-weight:650}
svg.mermaid-svg-blueprint .node rect,svg.mermaid-svg-blueprint rect.actor,svg.mermaid-svg-blueprint rect.actor-top,svg.mermaid-svg-blueprint rect.actor-bottom,svg.mermaid-svg-blueprint rect.note,svg.mermaid-svg-blueprint .classGroup rect,svg.mermaid-svg-blueprint rect.entityBox,svg.mermaid-svg-blueprint .statediagram-state rect,svg.mermaid-svg-blueprint .stateGroup rect,svg.mermaid-svg-blueprint .mindmap-node rect,svg.mermaid-svg-blueprint .timeline-node rect,svg.mermaid-svg-blueprint .kanban-item rect,svg.mermaid-svg-blueprint .block rect{fill:#fbfefe!important;stroke:#85aab2!important;stroke-width:1.5px!important}
svg.mermaid-svg-blueprint .node polygon,svg.mermaid-svg-blueprint .node circle,svg.mermaid-svg-blueprint .node ellipse,svg.mermaid-svg-blueprint .node path,svg.mermaid-svg-blueprint .statediagram-state circle,svg.mermaid-svg-blueprint .state-start,svg.mermaid-svg-blueprint .state-end{stroke:#85aab2!important;stroke-width:1.5px!important}
svg.mermaid-svg-blueprint .cluster rect,svg.mermaid-svg-blueprint .cluster polygon,svg.mermaid-svg-blueprint .cluster path{fill:#f4fafb!important;stroke:#b8d1d6!important;stroke-width:1.2px!important;stroke-dasharray:6 5}
svg.mermaid-svg-blueprint .flowchart-link,svg.mermaid-svg-blueprint .edgePath .path,svg.mermaid-svg-blueprint .relation,svg.mermaid-svg-blueprint .relationshipLine,svg.mermaid-svg-blueprint .actor-line,svg.mermaid-svg-blueprint .messageLine0,svg.mermaid-svg-blueprint .messageLine1,svg.mermaid-svg-blueprint .loopLine,svg.mermaid-svg-blueprint .transition,svg.mermaid-svg-blueprint .timeline-line{stroke:#4d7b84!important;stroke-width:1.9px!important;stroke-linecap:round;stroke-linejoin:round}
svg.mermaid-svg-blueprint marker path,svg.mermaid-svg-blueprint .marker{fill:#4d7b84!important;stroke:#4d7b84!important}
svg.mermaid-svg-blueprint .edgeLabel rect,svg.mermaid-svg-blueprint .labelBkg{fill:#f9fcfd!important;stroke:#c9dade!important;opacity:.97!important}
svg.mermaid-svg-blueprint rect.note{fill:#eaf5f7!important;stroke:#85aab2!important}
svg.mermaid-svg-blueprint .activation0,svg.mermaid-svg-blueprint .activation1,svg.mermaid-svg-blueprint .activation2{fill:#dceff2!important;stroke:#286b78!important}
svg.mermaid-svg-blueprint .attributeBoxEven,svg.mermaid-svg-blueprint .attributeBoxOdd{fill:#f4fafb!important;stroke:#c9dade!important}
svg.mermaid-svg-blueprint .task{stroke:#286b78!important;stroke-width:1.2px!important}
svg.mermaid-svg-blueprint .section0,svg.mermaid-svg-blueprint .section2{fill:#eaf5f7!important}
svg.mermaid-svg-blueprint .section1,svg.mermaid-svg-blueprint .section3{fill:#f4fafb!important}
svg.mermaid-svg-blueprint .grid .tick line,svg.mermaid-svg-blueprint .tick line{stroke:#c9dade!important}
svg.mermaid-svg-blueprint .pieTitleText,svg.mermaid-svg-blueprint .legend text{fill:#1c343c!important}
svg.mermaid-svg-blueprint .pieCircle{stroke:#f9fcfd!important;stroke-width:3px!important}
svg.mermaid-svg-blueprint foreignObject>div{color:#1c343c!important;line-height:1.35}
`;
function applyMermaidBlueprint(svg,kind){
  if(!svg||svg.dataset.learnBlueprint==='1')return;
  svg.dataset.learnBlueprint='1';
  const slug=String(kind||'diagram').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
  svg.classList.add('mermaid-svg-blueprint',`mermaid-svg-${slug||'diagram'}`);
  svg.setAttribute('preserveAspectRatio','xMidYMid meet');
  const ns='http://www.w3.org/2000/svg';
  let defs=svg.querySelector(':scope > defs');
  if(!defs){defs=document.createElementNS(ns,'defs');svg.insertBefore(defs,svg.firstChild)}
  const style=document.createElementNS(ns,'style');style.textContent=mermaidBlueprintCss;defs.appendChild(style);
  const filterId=`learn-mermaid-shadow-${++mermaidBlueprintSerial}`;
  const filter=document.createElementNS(ns,'filter');filter.id=filterId;filter.setAttribute('x','-20%');filter.setAttribute('y','-20%');filter.setAttribute('width','140%');filter.setAttribute('height','150%');
  const shadow=document.createElementNS(ns,'feDropShadow');shadow.setAttribute('dx','0');shadow.setAttribute('dy','3');shadow.setAttribute('stdDeviation','3');shadow.setAttribute('flood-color','#204852');shadow.setAttribute('flood-opacity','.09');filter.appendChild(shadow);defs.appendChild(filter);
  const radius={FLOWCHART:14,CLASS:13,STATE:16,SEQUENCE:11,ER:13,GANTT:7,MINDMAP:16,TIMELINE:13,JOURNEY:11,'GIT GRAPH':9,QUADRANT:10,'XY CHART':9,SANKEY:9,BLOCK:13,PACKET:9,ARCHITECTURE:14,KANBAN:13,REQUIREMENT:13,C4:13,DIAGRAM:12}[kind]||12;
  for(const rect of svg.querySelectorAll('rect')){
    if(rect.closest('defs'))continue;
    const className=rect.getAttribute('class')||'';
    const parentClass=rect.parentElement?.getAttribute('class')||'';
    const labelRect=rect.closest('.edgeLabel')||className.includes('labelBkg');
    const background=/background|grid/i.test(`${className} ${parentClass}`)&&(Number(rect.getAttribute('x')||0)===0&&Number(rect.getAttribute('y')||0)===0);
    if(background)continue;
    const r=labelRect?8:radius;
    rect.setAttribute('rx',String(r));rect.setAttribute('ry',String(r));
  }
  const nodeShapes=svg.querySelectorAll('.node rect,.node polygon,.node circle,.node ellipse,.node path,rect.actor,rect.note,.classGroup rect,rect.entityBox,.statediagram-state rect,.stateGroup rect,.mindmap-node rect,.timeline-node rect,.kanban-item rect,.block rect');
  for(const shape of nodeShapes)shape.setAttribute('filter',`url(#${filterId})`);
  if(kind==='FLOWCHART')for(const rect of svg.querySelectorAll('.node rect')){rect.setAttribute('rx','14');rect.setAttribute('ry','14')}
  if(kind==='CLASS')for(const rect of svg.querySelectorAll('.node rect,.classGroup rect')){rect.setAttribute('rx','13');rect.setAttribute('ry','13')}
  if(kind==='STATE')for(const rect of svg.querySelectorAll('.node rect,.statediagram-state rect,.stateGroup rect')){rect.setAttribute('rx','16');rect.setAttribute('ry','16')}
  if(kind==='SEQUENCE')for(const rect of svg.querySelectorAll('rect.actor,rect.note,rect[class*="activation"]')){rect.setAttribute('rx','11');rect.setAttribute('ry','11')}
  if(kind==='ER')for(const rect of svg.querySelectorAll('rect.entityBox,.node rect')){rect.setAttribute('rx','13');rect.setAttribute('ry','13')}
  if(kind==='PIE'){
    const palette=['#286b78','#5d8f77','#a37b4e','#85aab2','#8a6f9b','#b36d6a','#648a9a','#a9a268'];
    [...svg.querySelectorAll('.pieCircle')].forEach((slice,index)=>{slice.style.setProperty('fill',palette[index%palette.length],'important');slice.style.setProperty('stroke','#f9fcfd','important');slice.style.setProperty('stroke-width','3px','important')});
  }
}
function closeExpandedDiagram(){const box=document.querySelector('.mermaid-wrap.is-expanded');if(!box)return;box.classList.remove('is-expanded');box.querySelector('.mermaid-expand')?.setAttribute('aria-label','図を拡大');document.body.classList.remove('diagram-expanded')}
document.addEventListener('click',event=>{const button=event.target.closest('.mermaid-expand');if(!button)return;const box=button.closest('.mermaid-wrap');if(!box)return;const opening=!box.classList.contains('is-expanded');closeExpandedDiagram();if(opening){box.classList.add('is-expanded');button.setAttribute('aria-label','拡大表示を閉じる');document.body.classList.add('diagram-expanded')}});
document.addEventListener('keydown',event=>{if(event.key==='Escape')closeExpandedDiagram()});
async function renderMermaid(root){if(!root)return;const codes=[...root.querySelectorAll('code.language-mermaid')];for(const code of codes){const pre=code.closest('pre'),wrap=pre?.closest('.highlighter-rouge')||pre;if(!wrap)continue;const source=code.textContent||'',kind=mermaidKind(source),box=document.createElement('div'),head=document.createElement('div'),kicker=document.createElement('span'),type=document.createElement('span'),expand=document.createElement('button'),stage=document.createElement('div'),graph=document.createElement('div');box.className='mermaid-wrap mermaid-blueprint';box.dataset.diagramType=kind;head.className='mermaid-frame-head';kicker.className='mermaid-frame-kicker';kicker.textContent='BLUEPRINT';type.className='mermaid-frame-kind';type.textContent=kind;expand.className='mermaid-expand';expand.type='button';expand.setAttribute('aria-label','図を拡大');expand.textContent='⛶';stage.className='mermaid-stage';graph.className='mermaid';graph.textContent=source;head.append(kicker,type,expand);stage.appendChild(graph);box.append(head,stage);wrap.replaceWith(box)}const mermaid=await getMermaid();const nodes=[...root.querySelectorAll('.mermaid:not([data-processed])')];if(nodes.length)await mermaid.run({nodes});for(const box of root.querySelectorAll('.mermaid-wrap')){const svg=box.querySelector('svg');if(!svg)continue;svg.removeAttribute('height');svg.setAttribute('role','img');svg.setAttribute('aria-label',`${box.dataset.diagramType||'Diagram'} diagram`);applyMermaidBlueprint(svg,box.dataset.diagramType||'DIAGRAM')}}
function sectionNodes(name){const h=headings.find(x=>x.textContent.trim()===name);if(!h)return[];const nodes=[h];let n=h.nextElementSibling;while(n&&n.tagName!=='H2'){nodes.push(n);n=n.nextElementSibling}return nodes}function closeModal(){modalBackdrop?.classList.remove('open');modalBackdrop?.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open')}document.getElementById('revision-modal-close')?.addEventListener('click',closeModal);modalBackdrop?.addEventListener('click',e=>{if(e.target===modalBackdrop)closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modalBackdrop?.classList.contains('open'))closeModal()});
async function getMarked(){if(marked)return marked;const mod=await import('https://cdn.jsdelivr.net/npm/marked@15/+esm');marked=mod.marked;return marked}async function fetchRevisionMarkdown(commit){const url=`https://raw.githubusercontent.com/__LEARN_REPOSITORY__/${commit}/${articlePath.split('/').map(encodeURIComponent).join('/')}`;const res=await fetch(url);if(!res.ok)throw new Error(`raw ${res.status}`);return await res.text()}async function fetchPatch(commit){const res=await fetch(`https://api.github.com/repos/__LEARN_REPOSITORY__/commits/${commit}`,{headers:{Accept:'application/vnd.github+json'}});if(!res.ok)throw new Error(`commit ${res.status}`);const data=await res.json();return(data.files||[]).find(f=>f.filename===articlePath)?.patch||''}function extractSectionMarkdown(md,heading){const lines=md.split('\n');const target=`## ${heading}`;const start=lines.findIndex(l=>l.trim()===target);if(start<0)return'';let end=lines.length;for(let i=start+1;i<lines.length;i++){if(/^##\s+/.test(lines[i])){end=i;break}}return lines.slice(start,end).join('\n').trim()}function extractSectionDiff(patch,heading){if(!patch)return'';const lines=patch.split('\n');const marker=`## ${heading}`;let start=lines.findIndex(l=>l.replace(/^[ +\-]/,'').trim()===marker);if(start<0)return'';while(start>0&&!lines[start].startsWith('@@'))start--;let end=lines.length;for(let i=start+1;i<lines.length;i++){const plain=lines[i].replace(/^[ +\-]/,'').trim();if(/^##\s+/.test(plain)&&plain!==marker){end=i;break}if(i>start+1&&lines[i].startsWith('@@')){end=i;break}}return lines.slice(start,end).join('\n')}function classifyChange(diff,heading){const lines=diff.split('\n');const added=lines.some(l=>l.startsWith('+')&&l.slice(1).trim()===`## ${heading}`);const removed=lines.some(l=>l.startsWith('-')&&l.slice(1).trim()===`## ${heading}`);return added&&!removed?'added':'changed'}function renderDiff(patch){if(!patch)return'<div class="diff-note">この項目のText差分を取得できませんでした。</div>';return patch.split('\n').map(line=>{let cls='';if(line.startsWith('+')&&!line.startsWith('+++'))cls='diff-add';else if(line.startsWith('-')&&!line.startsWith('---'))cls='diff-del';else if(line.startsWith('@@'))cls='diff-meta';return`<span class="diff-line ${cls}">${escapeHtml(line)}</span>`}).join('')}
async function openRevision(index){const update=updates[index];if(!update)return;modalBackdrop.classList.add('open');modalBackdrop.setAttribute('aria-hidden','false');document.body.classList.add('modal-open');document.getElementById('revision-modal-date').textContent=update.date||'';document.getElementById('revision-modal-title').textContent=update.title||'';document.getElementById('revision-modal-summary').textContent=update.summary||'';modalBody.innerHTML='<div class="modal-loading">変更内容を読み込んでいます…</div>';try{const[md,patch,parser]=await Promise.all([fetchRevisionMarkdown(update.commit),fetchPatch(update.commit),getMarked()]);currentPatch=patch;const parts=[];for(const change of update.changes||[]){const sectionMd=extractSectionMarkdown(md,change.heading);const itemDiff=extractSectionDiff(patch,change.heading);const kind=classifyChange(itemDiff,change.heading);parts.push(`<article class="modal-change" data-heading="${escapeHtml(change.heading)}"><div class="modal-change-head"><div><div class="modal-change-title">${escapeHtml(change.heading)} <span class="modal-kind ${kind}">${kind==='added'?'追加':'変更'}</span></div><div class="modal-change-label">${escapeHtml(change.label||'')}</div></div></div><div class="snapshot ${kind}">${sectionMd?parser.parse(sectionMd):'<p>この更新時点のセクションを取得できませんでした。</p>'}</div><div class="change-actions"><button class="change-jump" type="button">記事の該当箇所へ</button><button class="item-diff-toggle" type="button">この項目の差分を見る</button></div><div class="diff-box item-diff">${renderDiff(itemDiff)}</div></article>`)}parts.push(`<div class="modal-footer"><div class="modal-footer-row"><button class="full-diff-toggle" type="button">この更新の全差分を見る</button><a href="https://github.com/__LEARN_REPOSITORY__/commit/${encodeURIComponent(update.commit)}" target="_blank" rel="noopener">GitHubでCommitを見る</a></div><div class="diff-box full-diff">${renderDiff(patch)}</div></div>`);modalBody.innerHTML=parts.join('');await renderMermaid(modalBody)}catch(error){modalBody.innerHTML='<div class="modal-error">変更内容を取得できませんでした。GitHubのCommitから確認してください。</div>'}}
for(const row of document.querySelectorAll('.revision-row'))row.addEventListener('click',()=>openRevision(Number(row.dataset.revision)));modalBody?.addEventListener('click',e=>{const change=e.target.closest('.modal-change');if(e.target.closest('.change-jump')&&change){const nodes=sectionNodes(change.dataset.heading);closeModal();if(nodes.length){nodes[0].classList.add('change-focus');nodes[0].scrollIntoView({behavior:'smooth',block:'start'});setTimeout(()=>nodes[0].classList.remove('change-focus'),3200)}}const itemBtn=e.target.closest('.item-diff-toggle');if(itemBtn&&change){const box=change.querySelector('.item-diff');box.classList.toggle('open');itemBtn.textContent=box.classList.contains('open')?'差分を閉じる':'この項目の差分を見る'}const fullBtn=e.target.closest('.full-diff-toggle');if(fullBtn){const box=modalBody.querySelector('.full-diff');box.classList.toggle('open');fullBtn.textContent=box.classList.contains('open')?'全差分を閉じる':'この更新の全差分を見る'}});
const languageMeta={javascript:['JavaScript','#f1e05a'],js:['JavaScript','#f1e05a'],typescript:['TypeScript','#3178c6'],ts:['TypeScript','#3178c6'],jsx:['React / JSX','#61dafb'],tsx:['React / TSX','#61dafb'],solidity:['Solidity','#6f7fa8'],rust:['Rust','#dea584'],go:['Go','#00add8'],python:['Python','#3776ab'],json:['JSON','#d4a72c'],yaml:['YAML','#cb171e'],yml:['YAML','#cb171e'],bash:['Bash','#4eaa25'],sh:['Shell','#4eaa25'],html:['HTML','#e34c26'],css:['CSS','#563d7c'],sql:['SQL','#e38c00'],text:['Text','#8b949e']};function detectLanguage(pre){for(const node of[pre,pre.querySelector('code')].filter(Boolean))for(const cls of node.classList||[])if(cls.startsWith('language-'))return cls.slice(9).toLowerCase();return'text'}for(const pre of content.querySelectorAll('pre')){const lang=detectLanguage(pre);if(lang==='mermaid')continue;const meta=languageMeta[lang]||[lang,'#8b949e'],wrap=pre.closest('.highlighter-rouge')||pre;wrap.classList.add('code-block');wrap.dataset.language=meta[0];wrap.style.setProperty('--code-accent',meta[1])}await renderMermaid(content)
