const SCALAR_RE=/^([A-Za-z_][A-Za-z0-9_-]*):\s*(.*?)\s*$/;
const SAFE_ID=/^[A-Za-z0-9][A-Za-z0-9._-]*$/;

export function parseFrontMatter(source){const lines=String(source).replace(/\r\n/g,'\n').replace(/\r/g,'\n').split('\n');if(lines[0]!=='---')throw new Error('front_matter_missing');const end=lines.indexOf('---',1);if(end<0)throw new Error('front_matter_unclosed');const front=lines.slice(1,end),body=lines.slice(end+1),data={};for(const line of front){const m=line.match(SCALAR_RE);if(!m)continue;let value=m[2].trim();if(value.length>=2&&value[0]===value.at(-1)&&['"',"'"].includes(value[0]))value=value.slice(1,-1);data[m[1]]=value;}return{front,body,data};}
function formatValue(value){if(typeof value==='boolean')return value?'true':'false';if(typeof value==='number'&&Number.isFinite(value))return String(value);const text=String(value);if(/^[A-Za-z0-9_.-]+$/.test(text))return text;return JSON.stringify(text);}
export function setFrontField(front,key,value){const index=front.findIndex(line=>line.match(SCALAR_RE)?.[1]===key);if(value===null||value===undefined||value===''){if(index>=0)front.splice(index,1);return;}const line=`${key}: ${formatValue(value)}`;if(index>=0){front[index]=line;return;}const preferred={directoryId:['placementLocked','domainId'],placementLocked:['domainId'],order:['chapter','directoryId','domainId']};for(const anchor of preferred[key]||[]){const at=front.findIndex(item=>item.match(SCALAR_RE)?.[1]===anchor);if(at>=0){front.splice(at,0,line);return;}}front.push(line);}
export function serializeFrontMatter(doc){return ['---',...doc.front,'---',...doc.body].join('\n').replace(/\n*$/,'\n');}
export function extractBodySource(source){const doc=parseFrontMatter(source);if(doc.data.type==='Directory')throw new Error('not_note');return doc.body.join('\n').replace(/^\n/,'').replace(/\n*$/,'\n');}
export function updateBodySource(source,body){const doc=parseFrontMatter(source);if(doc.data.type==='Directory')throw new Error('not_note');let value=String(body??'').replace(/\r\n/g,'\n').replace(/\r/g,'\n').replace(/^\n+/,'');if(!value.trim())throw new Error('invalid_body');if(value.length>500000)throw new Error('body_too_large');value=value.replace(/\n*$/,'');doc.body=['',...value.split('\n')];return serializeFrontMatter(doc);}
export function normalizeContentPath(value){const path=String(value||'').trim().replace(/^\/+/, '');if(!/^contents\/[A-Za-z0-9._/-]+\.md$/.test(path)||path.includes('..')||path.includes('//'))throw new Error('invalid_content_path');return path;}
export function normalizeRouteFilePath(value){const path=String(value||'').trim().replace(/^\/+/, '');if(!/^src\/pages\/[A-Za-z0-9._/-]+\.astro$/.test(path)||path.includes('..')||path.includes('//'))throw new Error('invalid_route_path');return path;}
export function updateMetadataSource(source,{title,description,order}){const doc=parseFrontMatter(source);if(title!==undefined){const value=String(title).trim();if(!value||value.length>180)throw new Error('invalid_title');setFrontField(doc.front,'title',value);}if(description!==undefined){const value=String(description).trim();if(!value||value.length>1000)throw new Error('invalid_description');setFrontField(doc.front,'description',value);}if(order!==undefined){const value=Number(order);if(!Number.isInteger(value)||value<0||value>999999)throw new Error('invalid_order');setFrontField(doc.front,'order',value);}return serializeFrontMatter(doc);}
export function updatePlacementSource(source,target){const doc=parseFrontMatter(source);if(doc.data.type!=='Directory'&&String(doc.data.placementLocked||'').toLowerCase()==='true')throw new Error('placement_locked');const domainId=String(target.domainId||'').trim(),domainName=String(target.domainName||'').trim();if(!SAFE_ID.test(domainId)||!domainName)throw new Error('invalid_target_domain');if(doc.data.type==='Directory'&&(!target.collectionId||!target.collectionName))throw new Error('invalid_target_collection');setFrontField(doc.front,'domainId',domainId);setFrontField(doc.front,'domainName',domainName);if(target.collectionId){if(!SAFE_ID.test(String(target.collectionId))||!target.collectionName)throw new Error('invalid_target_collection');setFrontField(doc.front,'collectionId',String(target.collectionId));setFrontField(doc.front,'collectionName',String(target.collectionName));}else{setFrontField(doc.front,'collectionId',null);setFrontField(doc.front,'collectionName',null);}setFrontField(doc.front,'directoryId',target.directoryId||null);const order=Number(target.order);if(!Number.isInteger(order)||order<0||order>999999)throw new Error('invalid_order');setFrontField(doc.front,'order',order);return serializeFrontMatter(doc);}
export function updatePlacementLockSource(source,locked){const doc=parseFrontMatter(source);if(doc.data.type==='Directory')throw new Error('not_note');setFrontField(doc.front,'placementLocked',Boolean(locked));return serializeFrontMatter(doc);}
export function createDirectorySource(input){const id=String(input.id||'').trim(),title=String(input.title||'').trim(),description=String(input.description||'').trim();const permalink=String(input.permalink||'').trim(),domainId=String(input.domainId||'').trim(),domainName=String(input.domainName||'').trim();const collectionId=String(input.collectionId||'').trim(),collectionName=String(input.collectionName||'').trim();const order=Number(input.order);if(!SAFE_ID.test(id))throw new Error('invalid_id');if(!title||title.length>180)throw new Error('invalid_title');if(!description||description.length>1000)throw new Error('invalid_description');if(!/^\/[A-Za-z0-9._/-]+\/$/.test(permalink)||permalink.includes('..')||permalink.includes('//'))throw new Error('invalid_permalink');if(!SAFE_ID.test(domainId)||!domainName)throw new Error('invalid_domain');if(!SAFE_ID.test(collectionId)||!collectionName)throw new Error('invalid_collection');if(!Number.isInteger(order)||order<0||order>999999)throw new Error('invalid_order');const lines=['---',`id: ${formatValue(id)}`,`permalink: ${JSON.stringify(permalink)}`,`title: ${JSON.stringify(title)}`,`description: ${JSON.stringify(description)}`,'type: Directory',`order: ${order}`];if(input.directoryId)lines.push(`directoryId: ${formatValue(String(input.directoryId))}`);lines.push(`domainId: ${formatValue(domainId)}`,`domainName: ${JSON.stringify(domainName)}`,`collectionId: ${formatValue(collectionId)}`,`collectionName: ${JSON.stringify(collectionName)}`,'---','');return lines.join('\n');}
export function directoryRoutePath(permalink){const clean=String(permalink||'').trim();if(!/^\/[A-Za-z0-9._/-]+\/$/.test(clean)||clean.includes('..')||clean.includes('//'))throw new Error('invalid_permalink');return `src/pages/${clean.replace(/^\//,'')}index.astro`;}
export function directoryRouteSource(id,routePath){if(!SAFE_ID.test(String(id||'')))throw new Error('invalid_id');const route=normalizeRouteFilePath(routePath);const dir=route.replace(/^src\/pages\//,'').split('/').slice(0,-1);const up='../'.repeat(dir.length+1);return `---\nimport DirectoryRoute from '${up}components/DirectoryRoute.astro';\n---\n<DirectoryRoute id=${JSON.stringify(String(id))} />\n`;}
export function pathDomain(path){return normalizeContentPath(path).split('/')[1]||'';}
